apiVersion: v1
kind: Service
metadata:
  name: app-api
spec:
  selector:
    app.kubernetes.io/name: app-api
  ports:
  - name: "5432"
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    name: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app-api
  template:
    metadata:
      labels:
        service: app-api
    spec:
      containers:
      - name: app-api
        image: 460876709067.dkr.ecr.us-east-1.amazonaws.com/coworking-workspace:0.02
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5432
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5432
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: app-db
      restartPolicy: Always